//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetChantierApp1._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetChantierEntities : DbContext
    {
        public ProjetChantierEntities()
            : base("name=ProjetChantierEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<Equipe> Equipes { get; set; }
        public virtual DbSet<Materiaux> Materiauxes { get; set; }
        public virtual DbSet<Ouvrage> Ouvrages { get; set; }
        public virtual DbSet<Projet> Projets { get; set; }
        public virtual DbSet<Realiser> Realisers { get; set; }
        public virtual DbSet<Sous_Traitant> Sous_Traitant { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Fournir> Fournirs { get; set; }
    }
}
