//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfChantierApp1._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        public int ProjetID { get; set; }
        public Nullable<int> EquipeID { get; set; }
        public string NomProjet { get; set; }
        public string Date_Debut_Projet { get; set; }
        public string Date_Fin_Projet { get; set; }
    
        public virtual Equipe Equipe { get; set; }
    }
}
