//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfChantierApp1._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realiser
    {
        public int RealiserID { get; set; }
        public Nullable<int> EquipeID { get; set; }
        public Nullable<int> OuvrageID { get; set; }
        public string Observations { get; set; }
    
        public virtual Equipe Equipe { get; set; }
        public virtual Ouvrage Ouvrage { get; set; }
    }
}
