//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfChantierApp1._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        private string nomUser;
        private string psswrdUser;

        //Constructeur
        public Employe(string nomUser, string psswrdUser)
        {
            this.nomUser = nomUser;
            this.psswrdUser = psswrdUser;
        }

        public int EmployeID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> DateEmbauche { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> EquipeID { get; set; }
        public string PosteEmploi { get; set; }
        public string EmployeMotPasse { get; set; }
    
        public virtual Equipe Equipe { get; set; }
    }
}
