//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfChantierApp1._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouvrage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ouvrage()
        {
            this.Materiauxes = new HashSet<Materiaux>();
            this.Fournirs = new HashSet<Fournir>();
            this.Realisers = new HashSet<Realiser>();
            this.Sous_Traitant = new HashSet<Sous_Traitant>();
        }
    
        public int OuvrageID { get; set; }
        public string NomOuvrage { get; set; }
        public string Description_Ouvrage { get; set; }
        public Nullable<int> EquipeID { get; set; }
        public string Date_Debut_Ouvrage { get; set; }
        public string Date_Fin_Ouvrage { get; set; }
    
        public virtual Equipe Equipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiaux> Materiauxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fournir> Fournirs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realiser> Realisers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sous_Traitant> Sous_Traitant { get; set; }
    }
}
